module.exports = {
    fim: [
        "independent",
        "modified independent",
        "supervision",
        "minimum assistance",
        "moderate assistance",
        "maximal assistance",
        "total assistance",
    ],
    goals: [
        "eating",
        "grooming",
        "upper body dressing",
        "lower body dressing",
        "toileting",
        "toilet transfers",
        "tub transfers",
    ],
    verbalCues: [
        "no verbal cueing",
        "minimal verbal cueing",
        "moderate verbal cueing",
        "maximum verbal cueing",
        "total verbal cueing",
    ],
    plan: ["upgrade", "downgrade", "maintain"],
    armBikeNames: [
        "arm bike",
        "Omnicycle",
        "ergometer",
        "Colorado Cycle",
        "restorator",
    ],
    patientTerm: ["patient", "client", "resident"],
    extremities: ["BUE", "LUE", "RUE"],
    muscleGroups: [
        "bicep",
        "tricep",
        "deltoid",
        "trapezius",
        "pectoralis major",
        "wrist flexor",
        "wrist extensor",
        "grip",
        "forearm supinator",
        "forearm prontator",
    ],
    functionalActivityEducationTopics: [
        "purpose",
        "frequency",
        "duration",
        "proper technique",
        "sequencing",
        "rules and procedures",
        "initiation",
        "termination",
    ],
    upperBodyDressingVerbalCues: [
        "clothing placement prior to donning",
        "dressing affected extremity first",
        "undressing the affected side last",
        "pulling sleeves up to shoulders before donning",
        "pulling shirt down in back all the way",
        "use dressing stick for limited reach",
        "shift weight appropriately",
    ],
    interventionsUBDressing: [
        "adaptive equipment: reacher",
        "adaptive equipment: dressing stick",
        "repetition",
        "task simplification",
        "weight shifting practice",
        "challenge dynamic sitting balance",
    ],
    sittingBalance: [
        "normal",
        "good",
        "good-",
        "fair+",
        "fair",
        "fair-",
        "poor+",
        "poor",
        "poor-",
    ],
    care: [
        "Independent",
        "Setup or Clean Assistance",
        "Supervision",
        "Partial/Moderate Assistance",
        "Substantial/Maximal Assistance",
        "Dependent",
    ],
    groomingTasks: [
        "brushing teeth",
        "brushing dentures",
        "rinsing mouth",
        "washing/drying face",
        "washing/drying hands",
        "combing/brushing hair",
    ],
    groomingVerbalCues: [
        "applying toothpaste to the toothbrush",
        "screwing/unscrewing the toothpaste cap",
        "thoroughly brushing teeth",
        "thoroughly brushing dentures",
        "applying soap to washcloth",
        "drying face with dry towel",
        "thoroughly scrubbing hands with soap",
        "drying hands with dry towel",
        "brushing/combing hair entirely",
    ],
    interventionsGrooming: [
        "weighted or builtup handle",
        "adapted toothpaste opener",
        "task repetition",
        "task simplification",
        "item placement",
        "gross motor coordination for reaching",
        "fine motor coordination",
    ],
    position: ["seated", "standing", "supine with head of bed elevated"],
    location: ["bedroom", "bathroom"],
    coordination: [
        "normal",
        "good",
        "good-",
        "fair+",
        "fair",
        "fair-",
        "poor+",
        "poor",
        "poor-",
    ],
};

